"use client";

import { FormEvent, useEffect, useState } from "react";
import { Badge } from "@/components/badge";
import { fetchJson } from "@/lib/client";

interface ApiKey { id: string; label: string; prefix: string; createdAt: string; revokedAt?: string; }
interface User { email: string; role: string; createdAt: string; }

export default function SettingsPage() {
  const [user, setUser] = useState<User>(); const [keys, setKeys] = useState<ApiKey[]>([]); const [label, setLabel] = useState(""); const [token, setToken] = useState(""); const [message, setMessage] = useState("");
  async function load(): Promise<void> { try { const [account, keyData] = await Promise.all([fetchJson<{ user: User | null }>("/api/auth/me"), fetchJson<{ keys: ApiKey[] }>("/api/api-keys")]); if (account.user) setUser(account.user); setKeys(keyData.keys); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load settings"); } }
  useEffect(() => { void load(); }, []);
  async function createKey(event: FormEvent): Promise<void> { event.preventDefault(); try { const data = await fetchJson<{ key: ApiKey; token: string }>("/api/api-keys", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label }) }); setToken(data.token); setLabel(""); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create API key"); } }
  async function revoke(id: string): Promise<void> { try { await fetchJson(`/api/api-keys/${id}`, { method: "DELETE" }); setToken(""); await load(); setMessage("API key revoked. The raw token was never stored."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to revoke key"); } }
  return <section className="page"><div className="page-head"><div><p className="eyebrow">ACCOUNT + SECURITY SETTINGS</p><h1>Workspace settings</h1><p className="muted">Manage your local workspace, privacy defaults, and developer API keys.</p></div><Badge value={user?.role ?? "LOADING"} /></div>{message && <p className="notice">{message}</p>}<div className="grid grid-2"><article className="card"><p className="eyebrow">ACCOUNT</p><h2>{user?.email ?? "Loading account…"}</h2><div className="monitor"><div className="monitor-row"><span>Role</span><Badge value={user?.role ?? "—"} /></div><div className="monitor-row"><span>Workspace mode</span><Badge value="LOCAL RUNTIME" /></div><div className="monitor-row"><span>Default retention</span><span>Metadata + content hash</span></div></div><p className="notice warn" style={{ marginTop: 16 }}>This local runtime grants SECURITY_ANALYST access for dashboard evaluation. Multi-user deployment must use audited, server-side role provisioning.</p></article><article className="card"><p className="eyebrow">PRIVACY CENTER</p><h2>Retention controls</h2><div className="monitor"><div className="monitor-row"><span>Prompt text</span><Badge value="NOT RETAINED" /></div><div className="monitor-row"><span>Content hash</span><Badge value="RETAINED" /></div><div className="monitor-row"><span>Credential material</span><Badge value="COMMITMENT ONLY" /></div><div className="monitor-row"><span>API keys</span><Badge value="HASHED" /></div></div><p className="muted" style={{ fontSize: 12 }}>Production retention schedules must be configured by the deployment operator and aligned with applicable law.</p></article></div><div className="grid grid-2" style={{ marginTop: 16 }}><article className="card"><p className="eyebrow">DEVELOPER API KEY</p><h2>Create a scoped local key</h2><form onSubmit={createKey}><div className="form-field"><label htmlFor="key-label">Key label</label><input id="key-label" className="input" value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Local integration" minLength={2} required /></div><button className="btn btn-primary">Create API key</button></form>{token && <div className="notice warn" style={{ marginTop: 15 }}><strong>Copy this value now; it is shown once.</strong><code className="hash" style={{ display: "block", marginTop: 8 }}>{token}</code></div>}</article><article className="card"><p className="eyebrow">ACTIVE KEYS</p><h2>Key inventory</h2>{keys.length ? keys.map((key) => <div className="monitor-row" key={key.id}><span><strong>{key.label}</strong><small style={{ display: "block", color: "var(--muted)", marginTop: 3 }}>{key.prefix}… · {key.revokedAt ? "revoked" : "active"}</small></span>{key.revokedAt ? <Badge value="REVOKED" /> : <button className="btn btn-danger" onClick={() => revoke(key.id)}>Revoke</button>}</div>) : <p className="empty">No API keys created.</p>}</article></div></section>;
}
