import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { randomId } from "@/lib/crypto";
import { apiError, authenticated, body, csrfGuard, isResponse, rateLimit } from "@/lib/http";
import { makeContext, riskEngine } from "@/lib/risk-engine";
import { store } from "@/lib/store";
import type { TrustLevel } from "@/lib/types";
const trust = z.enum(["SYSTEM", "DEVELOPER", "AUTHORIZED_USER", "APPLICATION", "TOOL", "RETRIEVED_DATA", "WEB_CONTENT", "EXTERNAL_AGENT", "UNTRUSTED"]);
const schema = z.object({ content: z.string().min(1).max(12000), source: z.string().min(1).max(80).default("USER_REQUEST"), trustLevel: trust.default("AUTHORIZED_USER"), origin: z.string().max(160).default("console"), historyCount: z.number().int().min(0).max(100).default(0), context: z.array(z.object({ content: z.string().min(1).max(12000), source: z.string().min(1).max(80), trustLevel: trust, origin: z.string().max(160).default("external") })).max(10).default([]) });
export async function POST(request: NextRequest): Promise<NextResponse> { try { const limited = rateLimit(request); if (limited) return limited; const csrf = csrfGuard(request); if (csrf) return csrf; const user = await authenticated(); if (isResponse(user)) return user; const input = await body(request, schema); const source = input.source ?? "USER_REQUEST"; const trustLevel = input.trustLevel ?? "AUTHORIZED_USER"; const origin = input.origin ?? "console"; const contexts = [makeContext(input.content, source, trustLevel as TrustLevel, origin), ...(input.context ?? []).map((item) => makeContext(item.content, item.source, item.trustLevel as TrustLevel, item.origin ?? "external"))]; const assessment = riskEngine.analyzeRequest(contexts, input.historyCount ?? 0); store.addEvent({ id: `evt_${randomId(10)}`, userId: user.id, eventType: "SECURITY_ASSESSMENT", severity: assessment.riskLevel === "CRITICAL" ? "CRITICAL" : assessment.riskLevel, riskScore: assessment.riskScore, source, contentHash: contexts[0].contentHash, decision: assessment.recommendedAction, attackType: assessment.attackTypes[0], createdAt: new Date().toISOString(), metadata: { provenanceCount: contexts.length, confidence: assessment.confidence, retainedContent: false } }); return NextResponse.json({ assessment, context: contexts.map(({ content: _content, ...safe }) => safe) });
} catch (error) { return apiError(error); } }
